# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faf1fb661861874099556d6b9203fe3d23c785be43841d55db640d170e06ee17054d4b6572257b82265f1da258539b38382744ee130c63fd09f62118e232b64b

test:
  secret_key_base: e82a69105534097e4507c0159d95f3bdc2b5879bf73f4c391049acde87f89c307dd56ee71a2c102aa0fe5a89c95389bd7f855994a5a18f4faec4d02c9af0e524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
